export enum unit {
    nm = "nm",
    mikrom = "μm",
    mm = "mm",
    cm = "cm",
    dm = "dm",
    m = "m",
    km = "km",
    inch = "in",
    ft = "ft",
    yd = "yd",
    mi = "mi",
    NM = "NM",
    au = "au",
    lokiec = "ł",
  }
  export enum unitLabels {
    nm = "Nanometry",
    mikrom = "Mikrometry",
    mm = "Milimetry",
    cm = "Centymetry",
    dm = "Decymetry",
    m = "Metry",
    km = "Kilometry",
    inch = "Cale",
    ft = "Stopy",
    yd = "Jardy",
    mi = "Mile",
    NM = "Mile morskie",
    au = "Jednostka astronomiczna",
    lokiec = "Łokcie",
};