export enum unitLength {
    nm = "nm",
    mikrom = "μm",
    mm = "mm",
    cm = "cm",
    dm = "dm",
    m = "m",
    km = "km",
    inch = "in",
    ft = "ft",
    yd = "yd",
    mi = "mi",
    NM = "NM",
    au = "au",
    lokiec = "ł",
  }
  export enum unitLengthLabels {
    nm = "Nanometry",
    mikrom = "Mikrometry",
    mm = "Milimetry",
    cm = "Centymetry",
    dm = "Decymetry",
    m = "Metry",
    km = "Kilometry",
    inch = "Cale",
    ft = "Stopy",
    yd = "Jardy",
    mi = "Mile",
    NM = "Mile morskie",
    au = "Jednostka astronomiczna",
    lokiec = "Łokcie",

};
export enum unitArea {
    nm2 = "nm²",
    mikrom2 = "μm²",
    mm2 = "mm²",
    cm2 = "cm²",
    dm2 = "dm²",
    m2 = "m²",
    km2 = "km²",
    inch2 = "in²",
    ft2 = "ft²",
    yd2 = "yd²",
    mi2 = "mi²",
    ac = "ac",
    a = "a",
    ha = "ha",
    morga = "m",
}
export enum unitAreaLabels {
    nm2 = "Nanometry kwadratowe",
    mikrom2 = "Mikrometry kwadratowe",
    mm2 = "Milimetry kwadratowe",
    cm2 = "Centymetry kwadratowe",
    dm2 = "Decymetry kwadratowe",
    m2 = "Metry kwadratowe",
    km2 = "Kilometry kwadratowe",
    inch2 = "Cale kwadratowe",
    ft2 = "Stopy kwadratowe",
    yd2 = "Jardy kwadratowe",
    mi2 = "Mile kwadratowe",
    ac = "Akry",
    a = "Ary",
    ha = "Hektary",
    morga = "Morgi nowopolskie:",
};
export enum unitTime {
    ns = "ns",
    mikros = "μs",
    ms = "ms",
    s = "s",
    q = "q",
    t = "t",
    min = "min",
    h = "h",
    d = "dni",
    tyg = "tyg",
    m = "msc",
    lat = "lat",
    dek = "dek",
    wiek = "w",
    tys = "mill",
}
export enum unitTimeLabels {
    ns = "Nanosekundy",
    mikros = "Mikrosekundy",
    ms = "Milisekundy",
    s = "Sekundy",
    q = "Kwarty",
    t = "Tercje",
    min = "Minuty",
    h = "Godziny",
    d = "Dni",
    tyg = "Tygodnie",
    m = "Miesiące (średnia)",
    lat = "Lata (średnia)",
    dek = "Dekady",
    wiek = "Wieki",
    tys = "Tysiąclecia",
};

